### ISSUE TITLE
Regarding the retrieval of JSON files

### ISSUE THREAD

**Issue by Wjhao7010** [mapeAAU/underwater_camera_calibration#1]
Hello author, I would like to know how to obtain the JSON files for cam1 and cam2 perspectives? Which points should be marked as coordinates for these two perspectives

**Comment by mapeAAU** [comment]
Hi, you can find examples of the reference files [here](https://github.com/mapeAAU/underwater_camera_calibration/tree/main/data/triangulate_using_id). In the given example we used the corners of an aquarium, where cam1 is located in front of the aquarium and cam2 is located above the aquarium. See our [paper](https://openaccess.thecvf.com/content_cvpr_2018_workshops/papers/w28/Pedersen_Camera_Calibration_for_CVPR_2018_paper.pdf) for more information on the setup (illustrated in figure 4) in the paper. The points are simply the corners of the aquarium, as described in the comments of the JSON reference files. 
A practical use case of the method is given in our [3D zebrafish tracking paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Pedersen_3D-ZeF_A_3D_Zebrafish_Tracking_Benchmark_Dataset_CVPR_2020_paper.pdf) with links to the [source code](https://github.com/mapeAAU/3D-ZeF) and [dataset](https://motchallenge.net/data/3D-ZeF20). Hope that helps!

**Comment by Wjhao7010** [comment]
Thank you very much for your reply! Your paper is really excellent, but I found that the comments in the JSON files of cam1 and cam2 in the examples are/* world<->camera correspondences for top view camera */, and I cannot determine which point of the water tank cam1 and cam2 are annotated with based on world coordinates and camera coordinates, which makes it difficult for me to operate correctly when processing my own dataset. I hope you can help me explain. Thank you very much!

**Comment by mapeAAU** [comment]
Aha, thank you for pointing out that error. And I can see that it is in fact the opposite of figure 4 of the paper; cam1 is the top camera and cam2 is the front camera in the example provided here on github. I fixed the typo and added a small note in the readme file to clarify.

**Comment by Wjhao7010** [comment]
It's okay, I have a small question. As shown in the picture, the dataset I shot myself is a front view taken from direction 1 and a top view taken from direction 2. If we annotate the water tank in this way, can we correctly obtain the final 3D coordinates
![0d348994b92c897c42b0e29d1522b2b](https://github.com/user-attachments/assets/3a1dd77e-6d99-4e4e-870b-d6a3d8f3b9df)

**Comment by mapeAAU** [comment]
Yes, it doesn't really matter where cameras are placed if you have calibrated your cameras properly, know the dimensions of the aquarium, and have updated the cam1 and cam2 reference files to fit your setup.

**Comment by Wjhao7010** [comment]
Thank you very much.I have another question about the GT value,the header information of the GT calculated according to the method in this paper includes these attributes:frame,err,err1,err2,3d_x,3d_y,3d_z,cam1_x,cam1_y,cam2_x,cam2_y,cam1_proj_x,cam1_proj_y,cam2_proj_x,cam2_proj_y,id.But I see that the GT information in your paper 3D-ZeF published in CVPR is as follows:frame,id,3d_x,3d_y,3d_z,camT_x,camT_y,camT_left,camT_top,camT_width,camT_width,camT_occlusion,camF_x,camF_y,camF_left,camF_top,camF_width,camF_width,camF_occlusion.So I would like to ask if there is a way to convert the GT information calculated in this paper into GT information in 3D ZeF? I want to create my own dataset for conducting experiments.Thank you very much for taking the time to answer my question amidst your busy schedule.

**Comment by mapeAAU** [comment]
First, there is an obvious error in the readme.txt file for the ground truth annotations from the 3D-ZeF dataset; the second occurence of "camT_width" and "camF_width" should be "camT_height" and "camF_height", respectively.
Second, I'm not sure I understand your question. The camera calibration and reconstruction procedure in this repo gives you an estimated 3D position and the associated reprojection error. We do not consider it as the "ground truth", instead we use a known distance between two objects (the colored balls depicted in the paper) as our ground truth for the experiments. In 3D-ZeF, however, the ground truth are our manually annotated 2D points and bounding boxes for each view and you cannot automatically get those by simply running a script. I don't know if this answers your question?

**Comment by Wjhao7010** [comment]
Thank you very much for your reply. I have seen the error in the readme. txt file in 3DZeF. Your answer has solved part of my problem. I would like to know if the 3D position and related reprojection error estimated using the code in this paper can be used as GT, because I want to build a 3D dataset similar to 3DZeF myself, so I must obtain the true 3D position of the target. In other words, I have manually annotated the 2D image positions of two perspectives myself, and I want to obtain the 3D real position through some way. Is this feasible? Or can it only be done through the method described in the paper (colored balls depicted in the paper)?

**Comment by mapeAAU** [comment]
Yes, you can get the **estimated** 3D position based on your 2D annotations and use that as the ground truth; that's what we did in 3D-ZeF with the head-point annotations (we used the head as it is the only rigid part of a fish).
You may need to tweak the code a tiny bit to fit your data, but it should all be there.
